version: "3.8"

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgres/data
    environment:
      - POSTGRES_USER: bruss
      - POSTGRES_DB: bruss
      - POSTGRES_PASSWORD: ${BRUSS_DB_PASSWORD}

volumes:
  postgres_data:
